name: Windows
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    paths-ignore:
      - '*.gif'
      - '*.png'
      - '*.yml'
      - '*.md'
      - 'LICENSE'

jobs:
  build:
    name: "Build & Test"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
    steps:
      - name: "Cancel similar actions in progress"
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: "Checkout"
        uses: actions/checkout@main
        with:
          submodules: recursive

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: 'git base-devel'

      - name: Install dependencies + Build Arturo
        shell: msys2 {0}
        run: |
          pacman --noconfirm -S p7zip
          pacman --noconfirm -S mingw-w64-x86_64-gcc
          mkdir dist
          mkdir nim
          curl -L https://nim-lang.org/download/mingw64.zip -o dist/mingw64.zip
          curl -L https://nim-lang.org/download/dlls.zip -o dist/dlls.zip
          curl -L https://nim-lang.org/download/nim-1.4.0_x64.zip -o dist/nim.zip
          7z x dist/mingw64.zip -odist
          7z x dist/dlls.zip -obin
          7z x dist/nim.zip -onim
          
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
          export PATH="${{ github.workspace }}/bin":$PATH
          export PATH="${{ github.workspace }}/nim/nim-1.4.0/bin":$PATH
          echo "${{ github.workspace }}/nim/nim-1.4.0/bin" >> $GITHUB_PATH
          ls -la nim/nim-1.4.0
          ls -la nim/nim-1.4.0/bin 
          echo "$GITHUB_PATH"
          
          echo "Running nim"
          nim --version

          nimble build -Y "-d:MINI"

      - name: Upload Artifacts
        uses: 'actions/upload-artifact@v2'
        with:
          name: "arturo-mini-${{matrix.os}}"
          path: bin/arturo.exe